### ISSUE TITLE
One tiny question on the data transformation design doc

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/elasticdl#1872] opened 2020-03-24 21:56 UTC
> How if the table new_plate doesn't have the field used to train the model? How if there is no field named size, but a field diameter. We should allow users to use the latter as well.
`SELECT * FROM new_plates TO PREDICT price USING a_model COLUM normalize(diameter)`

Why not `SELECT *, diameter as size FROM new_plates TO PREDICT ...`?

**Comment by brightcoder01** [comment] 2020-03-25 03:00
> > How if the table new_plate doesn't have the field used to train the model? How if there is no field named size, but a field diameter. We should allow users to use the latter as well.
> > `SELECT * FROM new_plates TO PREDICT price USING a_model COLUM normalize(diameter)`
> 
> Why not `SELECT *, diameter as size FROM new_plates TO PREDICT ...`?

I think you means `SELECT *, (MAX(diameter) - MIN(diameter)) AS size from new_plates TO PREDICT`?

If so
1) The statement above is calculating the `SIZE` value from the table for prediction? not the value from the training table. And the latter is what we want.
2) If we deploy the trained model for serving, the logic for calculating `(diameter - min) / (max - min)` is saved inside the model if we use `COLUMN NORMALIZE(diameter)`. The logic inside `SELECT xxx FROM` can't be saved inside the trained model using `SELECT *, (MAX(diameter) - MIN(diameter)) AS size from new_plates`

**Comment by tonyyang-svail** [comment] 2020-03-25 04:34
> I think you means SELECT *, (MAX(diameter) - MIN(diameter)) AS size from new_plates TO PREDICT?

Nope.

> If so
> 1. The statement above is calculating the SIZE value from the table for prediction? not the value from the training table. And the latter is what we want.
> 1. If we deploy the trained model for serving, the logic for calculating (diameter - min) / (max - min) is saved inside the model if we use COLUMN NORMALIZE(diameter). The logic inside SELECT xxx FROM can't be saved inside the trained model using SELECT *, (MAX(diameter) - MIN(diameter)) AS size from new_plates

I absolutely agree.

My question is, if we write `SELECT * FROM new_plates TO PREDICT price USING a_model COLUM normalize(diameter)`, how can the trained model know column `normalize(diameter)` in prediction corresponds to the column`size` in training?

**Comment by brightcoder01** [comment] 2020-03-25 05:14
> My question is, if we write `SELECT * FROM new_plates TO PREDICT price USING a_model COLUM normalize(diameter)`, how can the trained model know column `normalize(diameter)` in prediction corresponds to the column`size` in training?

COLUMN normalized(diameter) will be converted a python code with feature column api or keras preprocessing layers. The python code contains the required parameters `min` and `max` as constants from data analysis.

1) For batch prediction, the trained model will contain the model structure containing feature column or keras preprocessing layers aligned with the weights.
2) For serving, the feature column and keras preprocessing layers will be serialized into the SavedModel.

**Comment by brightcoder01** [comment] 2020-12-22 08:50
The question in the issue is addressed, close this issue.

**Closed as completed by brightcoder01** 2020-12-22 08:50 UTC
